
<?php

return [
    'Filipino', 'Afghan', 'Albanian', 'Algerian', 'Andorran', 
    'Angolan', 'Antiguan or Barbudan', 'Argentine', 'Armenian', 
    'Australian', 'Austrian', 'Azerbaijani', 'Bahamian', 'Bahraini', 
    'Bengali', 'Barbadian', 'Belarusian', 'Belgian', 'Belizean', 
    'Beninese', 'Bhutanese', 'Bolivian', 'Bosnian or Herzegovinian', 
    'Botswanan', 'Brazilian', 'Bruneian', 'Bulgarian', 'Burkinabé', 
    'Burmese', 'Burundian', 'Cabo Verdean', 'Cambodian', 'Cameroonian', 
    'Canadian', 'Central African', 'Chadian', 'Chilean', 'Chinese', 
    'Colombian', 'Comorian', 'Congolese', 'Costa Rican', 'Ivorian', 
    'Croatian', 'Cuban', 'Cypriot', 'Czech', 'Danish', 'Djiboutian', 
    'Dominican', 'Timorese', 'Ecuadorian', 'Egyptian', 'Salvadoran', 
    'Eritrean', 'Estonian', 'Ethiopian', 'Fijian', 'Finnish', 'French', 
    'Gabonese', 'Gambian', 'Georgian', 'German', 'Ghanaian', 'Greek', 
    'Grenadian', 'Guatemalan', 'Guinean', 'Bissau-Guinean', 'Guyanese', 
    'Haitian', 'Honduran', 'Hungarian', 'Icelandic', 'Indian', 'Indonesian', 
    'Iranian', 'Iraqi', 'Irish', 'Israeli', 'Italian', 'Jamaican', 'Japanese', 
    'Jordanian', 'Kazakhstani', 'Kenyan', 'I-Kiribati', 'North Korean', 
    'South Korean', 'Kuwaiti', 'Kyrgyz', 'Lao', 'Latvian', 'Lebanese', 
    'Basotho', 'Liberian', 'Libyan', 'Liechtensteiner', 'Lithuanian', 
    'Luxembourgish', 'Macedonian', 'Malagasy', 'Malawian', 'Malaysian', 
    'Maldivian', 'Malian', 'Maltese', 'Marshallese', 'Mauritian', 'Mauritanian', 
    'Mexican', 'Micronesian', 'Moldovan', 'Monégasque', 'Mongolian', 
    'Montenegrin', 'Moroccan', 'Mozambican', 'Namibian', 'Nauruan', 
    'Nepali', 'Dutch', 'New Zealander', 'Nicaraguan', 'Nigerien', 'Nigerian', 
    'Norwegian', 'Omani', 'Pakistani', 'Palauan', 'Palestinian', 'Panamanian', 
    'Papuan', 'Paraguayan', 'Peruvian', 'Polish', 'Portuguese', 'Puerto Rican', 
    'Qatari', 'Romanian', 'Russian', 'Rwandan', 'Kittitian or Nevisian', 
    'Saint Lucian', 'Vincentian', 'Samoan', 'Sammarinese', 'São Toméan', 
    'Saudi', 'Senegalese', 'Serbian', 'Seychellois', 'Sierra Leonean', 
    'Singaporean', 'Slovak', 'Slovenian', 'Solomon Islander', 'Somali', 
    'South African', 'South Sudanese', 'Spanish', 'Sri Lankan', 'Sudanese', 
    'Surinamese', 'Swazi', 'Swedish', 'Swiss', 'Syrian', 'Tajikistani', 
    'Tanzanian', 'Thai', 'Togolese', 'Tongan', 'Trinidadian or Tobagonian', 
    'Tunisian', 'Turkish', 'Turkmen', 'Tuvaluan', 'Ugandan', 'Ukrainian', 
    'Emirati', 'British', 'American', 'Uruguayan', 'Uzbek', 'Ni-Vanuatu', 
    'Vatican', 'Venezuelan', 'Vietnamese', 'Yemeni', 'Zambian', 'Zimbabwean'
];